Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
import numpy as np

list_ = ['1' ,'2' ,'3' ,'4' ,'5' ]

array_list = np.array(object = list_)

In [2]:

print(type(list_))

print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [3]:
import numpy as np

list_ = ['1' ,'2' ,'3' ,'4' ,'5' ]

array_list = np.array(object = list_)

print('Every Element data type of list    :: \n')

for i in range(len(list_)):
    print(f' {i} : {type(i)}')

print('Every Element data type of arraylist    :: \n')

for j in range(len(array_list)):
    print(f' {j} : {type(j)}')

Every Element data type of list    :: 

 0 : <class 'int'>
 1 : <class 'int'>
 2 : <class 'int'>
 3 : <class 'int'>
 4 : <class 'int'>
Every Element data type of arraylist    :: 

 0 : <class 'int'>
 1 : <class 'int'>
 2 : <class 'int'>
 3 : <class 'int'>
 4 : <class 'int'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [4]:
import numpy as np

list_ = ['1' ,'2' ,'3' ,'4' ,'5' ]

arra_list = np.array(object = list_)

if type(list_) != type(arra_list): 
    print('Every Element data type of list    :: \n')

    for i in range(len(list_)):
        print(f' {i} : {type(i)}')

    print('Every Element data type of arraylist    :: \n')

    for j in range(len(arra_list)):
        print(f' {j} : {type(j)}')
else:
    print('list_ and arra_list are same datatype')

Every Element data type of list    :: 

 0 : <class 'int'>
 1 : <class 'int'>
 2 : <class 'int'>
 3 : <class 'int'>
 4 : <class 'int'>
Every Element data type of arraylist    :: 

 0 : <class 'int'>
 1 : <class 'int'>
 2 : <class 'int'>
 3 : <class 'int'>
 4 : <class 'int'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [5]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

# Shape is used for get  the dimensions of an array. 
print(num_array.shape)


(2, 3)


In [6]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

# size is used for get the size of an array or elements are present in the array. 
print(num_array.size)


6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [14]:
import numpy as np

arr = np.zeros((3,3))
print(arr)
print(arr.shape)
print(arr.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [32]:
import numpy as np

arr = np.identity(5, dtype=float)
print(arr)

print(arr.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
